### PR TITLE
Update repo data via GitHub API rather than scraping

### LINKED ISSUE #4: Ability to manage Repos
A way to manage `Repo` instances with a CMS, so they can be added and removed by a moderator

* [x] Manage existing library in CMS
* [x] Redirect old URLs (e.g. `/library/types/Microhouse` -> `/library/types/microhouse`)
* [x] Allow new repos to be added
* [x] Clean up database
* [x] Documentation

### PR DESCRIPTION
**Pull request by jonleighton**
Closes #4 

Necessary steps before deploying:

* Update production env configuration to include `git_hub_token`
* Update Heroku scheduler to run `rake github:refresh_all` rather than `rake github:scrape_all`

### CODE REVIEW

**Comment by jonleighton** [comment]
A style note: I noticed there are lots of methods in the codebase defined like:

``` ruby
def foo bar
```

Instead of:

``` ruby
def foo(bar)
```

I'm not a big fan of the former as I think it makes harder to visually differentiate the method name from the parameter names. It seems that [the Ruby style guide agrees with me](https://github.com/bbatsov/ruby-style-guide#method-parens), FWIW (although that's only the reckons of other people on the internet, there's nothing inherently "right" about it).

Similarly, when a method call spans multiple lines, I prefer to use parentheses to make it clearer where the call starts and ends:

``` ruby
foo(
  bar,
  baz
)
```

**Comment by johnrees** [comment]
Looks good to merge 👍  apart from the commit count being slightly off

`Repo.find_by(name: "Microhouse").git_hub_project.commits_count == 34`

but the current count is 36

screen shot 2017-02-21 at 17 02 54

I did a bit of digging and have a feeling it might be an API issue/limitation though, i.e. something out of our control.

I added `git_hub_token` to the heroku ENV

**Comment by johnrees** [comment]
Thoughts on code analysers? Should I add [Rubocop](https://github.com/bbatsov/rubocop)?

**Comment by johnrees** [comment]
BTW I've added a staging server https://staging.wikihouse.cc

It's forked from the main production server https://devcenter.heroku.com/articles/multiple-environments

Right now you can push any feature branches to it using

```
git remote add staging https://git.heroku.com/wikihousecc-staging.git
git push staging github-updater:master
```

if you create any migrations you'll need to run them manually after the push
```
heroku run rake db:migrate --app wikihousecc-staging
```

You can also run rake tasks with something like
```
heroku run rake github:refresh_all --app wikihousecc-staging
```

It's currently serving the code from this PR (hence the different count on the homepage).

screen shot 2017-02-21 at 17 35 51

I think pipelines might be a better fit though, so I'll look into those and then update the docs accordingly https://devcenter.heroku.com/articles/pipelines#deployment-with-pipelines

Ta

**Comment by jonleighton** [comment]
>  apart from the commit count being slightly off

Ah, I figured it out. It [doesn't count anonymous contributions by default](https://octokit.github.io/octokit.rb/Octokit/Client/Repositories.html#contributors-instance_method), but I can change that. (Incidentally, it was ridiculously hard to figure out how to count commits, I don't know why they don't have an easier API method for it... also the current solution will break if the number of contributors is so high that pagination kicks in, but I figured YAGNI.)

**Comment by jonleighton** [comment]
> Thoughts on code analysers? Should I add Rubocop?

We could do it via https://codeclimate.com/ ? Either way, should prob be done as a separate issue

**Comment by jonleighton** [comment]
https://github.com/wikihouseproject/wikihouse.cc/issues/26

**Pull request merged**
